### PR TITLE
Replace geo files with FileSets (proposal)

### PR DESCRIPTION
**Pull request by eliotjordan**
This PR makes substantial changes to the existing Geo PCDM model. Primarily, I removed the individual subclasses of FileSet, and instead added an attribute to FileSet (:geo_file_type) to distinguish between the various types. This is analogous to the mime_type attribute which doesn't work for geospatial objects at this point. Please consider this a proposal in which everything is up for discussion and debate.

An outstanding issue is to add individual buttons like 'attach vector file' instead of the generic 'attach a file' button. This would open a link on a new set of routes. Something like ```.../concern/container/:parent_id/file_sets/vector/new```. We could make use of hidden fields and drop downs for the file format. Also, the file format terminology could use some work.

Video demo of creating works and files: (Video isn't great quality. View it HD for better results)

https://vimeo.com/148118697

### CODE REVIEW

**Comment by eliotjordan** [comment]
Not sure why the coverage went down 48%?!? If anything, the coverage increased.

**Comment by eliotjordan** [comment]
I monkeyed around with the spec helper. Doh. :grin: Coverage is back where it should be.

**Comment by drh-stanford** [comment]
Nice video demo :)

**Comment by jrgriffiniii** [comment]
:+1:

**Comment by yulgit1** [comment]
Nice video.

Comment: Maybe a drop down box rather than input box for Geo File format, as the format types are controlled.

**Pull request merged**
