### PR TITLE
use provenance from configuration and put URIs into identifiers

### LINKED ISSUE #169: Use institution name as default for provenance
Use institution name as default for dc:provenance. The document builder (geoblacklight specifically) needs a provenance to build a layer slug.  Perhaps  slugs should come from `curation_concerns.institution_name` rather than provenance?

### PR DESCRIPTION
**Pull request by drh-stanford**
This PR fixes #169, but it requires the user to configure their instance to include a locale file with `geo_concerns.institution.uri` in it. Maybe we need to put that in a generator?

### CODE REVIEW

**Comment by eliotjordan** [comment]
@drh-stanford I think adding the locale file to the generator is a good idea.

**Comment by drh-stanford** [comment]
I added the locale config into the generator. I'm not sure whether I need to delete it from the root though (I copied it to the generator templates)...

**Comment by eliotjordan** [comment]
Makes sense to delete it from the root, otherwise you have to duplicate changes you make to it in the future.

**Comment by drh-stanford** [comment]
Ok, I deleted it from the config root. Should be ready to go now...

**Pull request merged**
